@startwbs 功能模块设计
title "教学辅助平台功能模块设计"
' 提供教学辅助平台，展示逻辑思维案例，提供编辑界面，程序提交、保存、运行
' 设计和实现符合逻辑思维编程语言：友好易于使用，体现不同逻辑思维模式
' 学生使用受控自然语言（CNL），系统将其转化成ASP等逻辑语言并运行得到答案
' 建立逻辑思维案例库，训练学生逻辑思维，设计算法将其自动转为逻辑程序
' 逻辑问题自动理解和求解（机器阅读）， 构建不同思维模式算法模型

' 构建教研平台，实现如下功能:
' 1、基于 ASP、ImLP语言的问题定义提交和运行测试、调试
' 2、基于 ImLP/ASP 的定义、演绎、溯因、归纳等思维模式的构建和友好编程界面，以及说明(需要定义 ASP/ImLP的更贴近自然的逻辑的语言的语言，需要花大量时间)
' 3、调研并进行案例库建设:思维游戏、考公逻辑推理题目、医学逻辑题目、法律逻辑题目、SAT题目、……，给出原题、分类标签、结果、求解的思维过程、大模型测试结果、增删改查、可视化
' 4、学生自建案例的增删改查

+ 教学辅助平台
++ 用户向导功能
+++ 在线阅读文档和教程
+++[#LightSalmon] 技术问答机器人
+++[#LightSalmon] 技术交流/问答社区

++ 用户管理
+++ 注册新用户
+++ 登录/登出
+++ 用户个人资料管理
+++ 用户权限管理

++ 编程实践功能
+++ "在线代码编辑器" as programCoder
++++ 编辑器格式设置
++++ 语法错误提示
+++ 程序保存和导出
+++ ImLP/ASP代码运行和调试


++ 逻辑推理实践功能
+++ 在线逻辑编辑器
+++[#LightSalmon] CNL模板模型选择
+++[#LightSalmon] CNL语法检测提示功能
+++ 逻辑内容保存和导出
+++ 逻辑内容推理
+++ 推理过程展示
+++[#LightSalmon] 逻辑问题自动理解
+++[#LightSalmon] 论证提取

++ 逻辑CNL转化功能
+++ CNL转为ASP/ImLP
+++[#LightSalmon] NL转为CNL

++ 案例展示功能
+++ 展示逻辑思维案例
+++ 查询/筛选逻辑思维案例
+++ "案例求解编辑器" as caseCoder
+++ 展示案例ASP表示
+++ 展示案例逻辑表示
+++[#LightSalmon] 案例解析展示
+++[#LightSalmon] 统计案例完成效果
+++[#LightSalmon] 案例问题论坛
+++[#LightSalmon] 案例笔记
+++[#LightSalmon] 案例反馈

++ 案例库编辑功能
+++ 新增案例
++++ 新增案例题目
++++ 新增案例ASP表达
++++ 新增案例逻辑表达
+++ 修改案例
++++ 修改案例题目
++++ 修改案例ASP表达
++++ 修改案例逻辑表达
+++ 审核案例修改

++ 平台管理功能
+++ 管理用户信息
+++[#LightSalmon] 监控/统计案例完成情况
+++[#LightSalmon] 管理用户反馈

' caseCoder -> programCoder

' ++ 课程管理
' +++ 创建新课程
' +++ 编辑和更新课程信息
' +++ 课程分类和标签
' +++ 课程搜索和过滤
' +++ 课程评价和评论

' ++ 学习资源管理
' +++ 上传和共享学习资料
' +++ 下载和保存学习资料
' +++ 在线阅读文档和教程
' +++ 视频教程和演示

' ++ 社区互动功能
' +++ 讨论论坛和社交平台
' +++ 用户间私信和通知
' +++ 问答功能和知识共享
' +++ 点赞和收藏功能

' ++ 学习进度和成绩管理功能
' +++ 课程学习进度跟踪
' +++ 学习计划和提醒功能
' +++ 作业和考试成绩管理
' +++ 学习证书和徽章颁发

@endwbs

@startwbs 功能模块划分
title "教学辅助平台功能模块划分"
' 提供教学辅助平台，展示逻辑思维案例，提供编辑界面，程序提交、保存、运行
' 设计和实现符合逻辑思维编程语言：友好易于使用，体现不同逻辑思维模式
' 学生使用受控自然语言（CNL），系统将其转化成ASP等逻辑语言并运行得到答案
' 建立逻辑思维案例库，训练学生逻辑思维，设计算法将其自动转为逻辑程序
' 逻辑问题自动理解和求解（机器阅读）， 构建不同思维模式算法模型

' 构建教研平台，实现如下功能:
' 1、基于 ASP、ImLP语言的问题定义提交和运行测试、调试
' 2、基于 ImLP/ASP 的定义、演绎、溯因、归纳等思维模式的构建和友好编程界面，以及说明(需要定义 ASP/ImLP的更贴近自然的逻辑的语言的语言，需要花大量时间)
' 3、调研并进行案例库建设:思维游戏、考公逻辑推理题目、医学逻辑题目、法律逻辑题目、SAT题目、……，给出原题、分类标签、结果、求解的思维过程、大模型测试结果、增删改查、可视化
' 4、学生自建案例的增删改查

+ 教学辅助平台
++ 用户向导功能


++ 用户管理


++ 编程实践功能



++ 逻辑推理实践功能


++ 逻辑CNL转化功能


++ 案例展示功能


++ 案例库编辑功能


++ 平台管理功能


' caseCoder -> programCoder

' ++ 课程管理
' +++ 创建新课程
' +++ 编辑和更新课程信息
' +++ 课程分类和标签
' +++ 课程搜索和过滤
' +++ 课程评价和评论

' ++ 学习资源管理
' +++ 上传和共享学习资料
' +++ 下载和保存学习资料
' +++ 在线阅读文档和教程
' +++ 视频教程和演示

' ++ 社区互动功能
' +++ 讨论论坛和社交平台
' +++ 用户间私信和通知
' +++ 问答功能和知识共享
' +++ 点赞和收藏功能

' ++ 学习进度和成绩管理功能
' +++ 课程学习进度跟踪
' +++ 学习计划和提醒功能
' +++ 作业和考试成绩管理
' +++ 学习证书和徽章颁发

@endwbs


@startmindmap 功能模块设计（横向）
title "教学辅助平台功能模块设计"

' skinparam linetype ortho
skinparam linetype ortho



' 提供教学辅助平台，展示逻辑思维案例，提供编辑界面，程序提交、保存、运行
' 设计和实现符合逻辑思维编程语言：友好易于使用，体现不同逻辑思维模式
' 学生使用受控自然语言（CNL），系统将其转化成ASP等逻辑语言并运行得到答案
' 建立逻辑思维案例库，训练学生逻辑思维，设计算法将其自动转为逻辑程序
' 逻辑问题自动理解和求解（机器阅读）， 构建不同思维模式算法模型

' 构建教研平台，实现如下功能:
' 1、基于 ASP、ImLP语言的问题定义提交和运行测试、调试
' 2、基于 ImLP/ASP 的定义、演绎、溯因、归纳等思维模式的构建和友好编程界面，以及说明(需要定义 ASP/ImLP的更贴近自然的逻辑的语言的语言，需要花大量时间)
' 3、调研并进行案例库建设:思维游戏、考公逻辑推理题目、医学逻辑题目、法律逻辑题目、SAT题目、……，给出原题、分类标签、结果、求解的思维过程、大模型测试结果、增删改查、可视化
' 4、学生自建案例的增删改查

<style>
node {
    RoundCorner 0
}

</style>

+ 教学辅助平台
++ 用户向导功能
+++ 在线阅读文档和教程
+++[#LightSalmon] 技术问答机器人
+++[#LightSalmon] 技术交流/问答社区

++ 用户管理
+++ 注册新用户
+++ 登录/登出
+++ 用户个人资料管理
+++ 用户权限管理

++ 编程实践功能
+++ "在线代码编辑器" as programCoder
++++ 编辑器格式设置
++++ 语法错误提示
+++ 程序保存和导出
+++ ImLP/ASP代码运行和调试


++ 逻辑推理实践功能
+++ 在线逻辑编辑器
+++[#LightSalmon] CNL模板模型选择
+++[#LightSalmon] CNL语法检测提示功能
+++ 逻辑内容保存和导出
+++ 逻辑内容推理
+++ 推理过程展示
+++[#LightSalmon] 逻辑问题自动理解
+++[#LightSalmon] 论证提取

++ 逻辑CNL转化功能
+++ CNL转为ASP/ImLP
+++[#LightSalmon] NL转为CNL

++ 案例展示功能
+++ 展示逻辑思维案例
+++ 查询/筛选逻辑思维案例
+++ "案例求解编辑器" as caseCoder
+++ 展示案例ASP表示
+++ 展示案例逻辑表示
+++[#LightSalmon] 案例解析展示
+++[#LightSalmon] 统计案例完成效果
+++[#LightSalmon] 案例问题论坛
+++[#LightSalmon] 案例笔记
+++[#LightSalmon] 案例反馈

++ 案例库编辑功能
+++ 新增案例
++++ 新增案例题目
++++ 新增案例ASP表达
++++ 新增案例逻辑表达
+++ 修改案例
++++ 修改案例题目
++++ 修改案例ASP表达
++++ 修改案例逻辑表达
+++ 审核案例修改

++ 平台管理功能
+++ 管理用户信息
+++[#LightSalmon] 监控/统计案例完成情况
+++[#LightSalmon] 管理用户反馈

' caseCoder -> programCoder

' ++ 课程管理
' +++ 创建新课程
' +++ 编辑和更新课程信息
' +++ 课程分类和标签
' +++ 课程搜索和过滤
' +++ 课程评价和评论

' ++ 学习资源管理
' +++ 上传和共享学习资料
' +++ 下载和保存学习资料
' +++ 在线阅读文档和教程
' +++ 视频教程和演示

' ++ 社区互动功能
' +++ 讨论论坛和社交平台
' +++ 用户间私信和通知
' +++ 问答功能和知识共享
' +++ 点赞和收藏功能

' ++ 学习进度和成绩管理功能
' +++ 课程学习进度跟踪
' +++ 学习计划和提醒功能
' +++ 作业和考试成绩管理
' +++ 学习证书和徽章颁发

@endmindmap