@startuml AF analysis
' left to right direction

circle p5
circle p1
circle p2
circle p3
circle p4

p5 -> p1
p1 -> p5

p3 -> p4 
p4 -> p3

p1 -> p3
p3 -> p1

@enduml


@startuml

skinparam nodesep 30
skinparam ranksep 30

circle A

A --> B
A --> C
C --> D
C --> E
C --> F

@enduml